version: '3.9'
services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
